/**
 * Soli Medical MICU (ICU-Sync) - Dexie.js Database & Local Persistent Store
 * 
 * Local-First IndexedDB architecture for 6 beds with offline persistence,
 * real-time reactive queries, and immutable clinical ledger.
 */

import Dexie, { Table } from 'dexie';
import {
  BedRecord,
  BedNumber,
  BedStatus,
  PatientDossier,
  TelemetryVitals,
  VentilatorParameters,
  InfusionPumpLine,
  FluidBalance24H,
  StatLabPanel,
  TransfusionTracker,
  SbarHandoverReport,
  ClinicalNote,
  Addendum,
  StaffMember,
  IcuUser,
  WardAuditLog,
  AcuityLevel,
  CodeStatus,
  Gender,
  IntakePathway,
  StaffRole,
  NoteType,
  VentilatorMode,
  AllergySeverity,
  PumpStatus,
  TransfusionProduct,
} from '../types/schema.ts';

export class ICUSyncDatabase extends Dexie {
  beds!: Table<BedRecord, BedNumber>;
  patients!: Table<PatientDossier, string>;
  vitals!: Table<TelemetryVitals, string>;
  ventilators!: Table<VentilatorParameters, string>;
  infusionPumps!: Table<InfusionPumpLine, string>;
  fluidBalances!: Table<FluidBalance24H, string>;
  statLabs!: Table<StatLabPanel, string>;
  transfusions!: Table<TransfusionTracker, string>;
  sbarHandovers!: Table<SbarHandoverReport, string>;
  clinicalNotes!: Table<ClinicalNote, string>;
  addendums!: Table<Addendum, string>;
  staff!: Table<StaffMember, string>;
  users!: Table<IcuUser, string>;
  auditLogs!: Table<WardAuditLog, string>;

  constructor() {
    super('SoliMedical_ICUSync_DB');

    this.version(1).stores({
      beds: 'bedNumber, status, currentPatientId',
      patients: 'id, mrn, nationalId, patientStatus, currentBedId, admissionDate, acuityLevel, fullNameEn, fullNameAr',
      vitals: 'id, bedId, patientId, timestamp',
      ventilators: 'id, bedId, patientId, timestamp',
      infusionPumps: 'id, bedId, patientId, pumpChannel, status',
      fluidBalances: 'id, bedId, patientId, periodStartTimestamp',
      statLabs: 'id, bedId, patientId, timestamp',
      transfusions: 'id, bedId, patientId, bloodGroup',
      sbarHandovers: 'id, bedId, patientId, shiftType, shiftDate, isLocked',
      clinicalNotes: 'id, bedId, patientId, noteType, authorId, timestamp, isImmutable',
      addendums: 'id, noteId, patientId, authorId, timestamp, isImmutable',
      staff: 'id, staffId, role, activeShift',
      users: 'uid, email, role, badgeId, isActive',
      auditLogs: 'id, timestamp, eventType, targetBedId, targetPatientMrn',
    });
  }
}

export const db = new ICUSyncDatabase();

// -------------------------------------------------------------
// Seed Database with Realistic Clinical Data (All 6 ICU Beds)
// -------------------------------------------------------------

export async function initializeDatabaseSeed(): Promise<void> {
  const bedsCount = await db.beds.count();
  if (bedsCount >= 6) {
    return; // Already initialized
  }

  await db.transaction('rw', [
    db.beds,
    db.patients,
    db.vitals,
    db.ventilators,
    db.infusionPumps,
    db.fluidBalances,
    db.statLabs,
    db.transfusions,
    db.sbarHandovers,
    db.clinicalNotes,
    db.addendums,
    db.staff,
    db.auditLogs,
  ], async () => {
    const nowIso = new Date().toISOString();
    const todayStr = nowIso.split('T')[0];

    // 1. Staff Seed
    const staffMembers: StaffMember[] = [
      {
        id: 'staff-01',
        staffId: '9042',
        nameEn: 'Dr. Hossam El-Din',
        nameAr: 'د. حسام الدين',
        role: StaffRole.CONSULTANT,
        specialization: 'Critical Care Medicine & Pulmonology',
        activeShift: 'NIGHT',
        assignedBeds: [BedNumber.BED_01, BedNumber.BED_02, BedNumber.BED_03, BedNumber.BED_04, BedNumber.BED_05, BedNumber.BED_06],
        licenseNumber: 'EGY-CCM-84910',
        isConsultantLead: true,
      },
      {
        id: 'staff-02',
        staffId: '9115',
        nameEn: 'Dr. Ahmed Tarek',
        nameAr: 'د. أحمد طارق',
        role: StaffRole.SPECIALIST,
        specialization: 'Intensive Care Specialist',
        activeShift: 'NIGHT',
        assignedBeds: [BedNumber.BED_04, BedNumber.BED_05, BedNumber.BED_06],
        licenseNumber: 'EGY-CCM-92014',
      },
      {
        id: 'staff-03',
        staffId: '9133',
        nameEn: 'Dr. Mona Shaker',
        nameAr: 'د. منى شاكر',
        role: StaffRole.RESIDENT,
        specialization: 'ICU Resident',
        activeShift: 'NIGHT',
        assignedBeds: [BedNumber.BED_01, BedNumber.BED_02, BedNumber.BED_03],
        licenseNumber: 'EGY-RES-48192',
      },
      {
        id: 'staff-04',
        staffId: '7721',
        nameEn: 'RN Sarah Kamal (BSN, CCRN)',
        nameAr: 'ممرضة سارة كمال',
        role: StaffRole.LEAD_RN,
        specialization: 'Critical Care Bed Supervisor',
        activeShift: 'NIGHT',
        assignedBeds: [BedNumber.BED_01, BedNumber.BED_02, BedNumber.BED_03, BedNumber.BED_04, BedNumber.BED_05, BedNumber.BED_06],
        licenseNumber: 'NUR-EGY-66291',
      },
    ];
    await db.staff.bulkPut(staffMembers);

    // 2. Patient Dossiers Seed
    const patient1: PatientDossier = {
      id: 'pat-01',
      mrn: '99281',
      fullNameEn: 'Hassan Farouk',
      fullNameAr: 'حسن فاروق',
      age: 54,
      gender: Gender.MALE,
      weightKg: 78,
      heightCm: 174,
      idealBodyWeightKg: 69.5,
      codeStatus: CodeStatus.FULL_CODE,
      primaryDiagnosisEn: 'Severe ARDS / Septic Shock / COPD Exacerbation History',
      primaryDiagnosisAr: 'متلازمة الضائقة التنفسية الحادة الشديدة وصدمة إنتانية',
      intakePathway: IntakePathway.STAT_CRITICAL,
      admissionDate: `${todayStr}T02:15:00.000Z`,
      currentBedId: BedNumber.BED_01,
      acuityLevel: AcuityLevel.CRITICAL_STAT,
      patientStatus: 'ACTIVE_ICU',
      allergies: [
        {
          id: 'all-01',
          allergen: 'PENICILLIN G (Beta-Lactams)',
          reaction: 'Severe Anaphylactic Shock & Laryngeal Edema',
          severity: AllergySeverity.FATAL_ANAPHYLAXIS,
          confirmedYear: 2021,
          isLocked: true,
          verifiedBy: 'Dr. Hossam El-Din',
          clinicalNote: 'Strict contraindication to all penicillins, amoxicillin, and cephalosporins.',
        },
      ],
      microbiologyHistory: [
        {
          id: 'mic-01',
          specimenSource: 'Sputum Culture',
          isolatedOrganism: 'MRSA (Methicillin-Resistant Staphylococcus aureus)',
          cultureDate: '2024-11-14',
          isResistant: true,
          resistantTo: ['Oxacillin', 'Penicillin', 'Cefoxitin'],
          sensitiveTo: ['Linezolid', 'Vancomycin', 'Daptomycin'],
          recommendedIsolation: 'Contact Precautions & Dedicated Equipment',
        },
      ],
      pastVisits: [
        {
          id: 'visit-01',
          admissionDate: '2024-11-10',
          dischargeDate: '2024-11-18',
          primaryDiagnosis: 'Severe CAP with Septic Shock',
          outcome: 'DISCHARGED_IMPROVED',
          attendingPhysicianName: 'Dr. Hossam El-Din',
          notes: 'Treated with Linezolid and lung-protective ventilation. Extubated day 5.',
        },
      ],
      attendingPhysician: {
        staffId: '9042',
        name: 'Dr. Hossam El-Din',
        role: StaffRole.CONSULTANT,
      },
      primaryNurse: {
        staffId: '7721',
        name: 'RN Sarah Kamal',
        role: StaffRole.LEAD_RN,
      },
      isolationPrecautions: ['MRSA Contact Isolation'],
      createdAt: nowIso,
      updatedAt: nowIso,
    };

    const patient2: PatientDossier = {
      id: 'pat-02',
      mrn: '33412',
      fullNameEn: 'Maryam Al-Sayed',
      fullNameAr: 'فاطمة السيد / مريم السيد',
      age: 48,
      gender: Gender.FEMALE,
      weightKg: 68,
      heightCm: 160,
      idealBodyWeightKg: 52.0,
      codeStatus: CodeStatus.FULL_CODE,
      primaryDiagnosisEn: 'DKA with Severe Metabolic Acidosis & AKI',
      primaryDiagnosisAr: 'حماض كيتوني سكري حاد وقصور كلوي حاد',
      intakePathway: IntakePathway.ER_REFERRAL,
      admissionDate: `${todayStr}T04:30:00.000Z`,
      currentBedId: BedNumber.BED_02,
      acuityLevel: AcuityLevel.GUARDED_STABLE,
      patientStatus: 'ACTIVE_ICU',
      allergies: [],
      microbiologyHistory: [],
      pastVisits: [],
      attendingPhysician: {
        staffId: '9042',
        name: 'Dr. Hossam El-Din',
        role: StaffRole.CONSULTANT,
      },
      primaryNurse: {
        staffId: '7721',
        name: 'RN Sarah Kamal',
        role: StaffRole.LEAD_RN,
      },
      createdAt: nowIso,
      updatedAt: nowIso,
    };

    const patient3: PatientDossier = {
      id: 'pat-03',
      mrn: 'ICU-992-814',
      fullNameEn: 'Mohamed Adel El-Sayed',
      fullNameAr: 'محمد عادل السيد',
      age: 62,
      gender: Gender.MALE,
      weightKg: 84,
      heightCm: 178,
      idealBodyWeightKg: 73.2,
      codeStatus: CodeStatus.FULL_CODE,
      primaryDiagnosisEn: 'Septic Shock secondary to Community-Acquired Pneumonia & Severe ARDS',
      primaryDiagnosisAr: 'صدمة إنتانية ومتلازمة الضائقة التنفسية الحادة الناتجة عن ذات الرئة',
      intakePathway: IntakePathway.STAT_CRITICAL,
      admissionDate: `${todayStr}T01:15:00.000Z`,
      currentBedId: BedNumber.BED_03,
      acuityLevel: AcuityLevel.CRITICAL_STAT,
      patientStatus: 'ACTIVE_ICU',
      allergies: [
        {
          id: 'all-03-1',
          allergen: 'Penicillin (Anaphylaxis)',
          reaction: 'Severe Bronchospasm and Cardiovascular Collapse',
          severity: AllergySeverity.FATAL_ANAPHYLAXIS,
          confirmedYear: 2021,
          isLocked: true,
          verifiedBy: 'Dr. Hossam El-Din',
        },
        {
          id: 'all-03-2',
          allergen: 'Sulfa Drugs',
          reaction: 'Severe generalized rash and urticaria',
          severity: AllergySeverity.SEVERE,
          isLocked: true,
          verifiedBy: 'Dr. Hossam El-Din',
        },
      ],
      microbiologyHistory: [],
      pastVisits: [
        {
          id: 'visit-03-1',
          admissionDate: '2021-06-12',
          dischargeDate: '2021-06-20',
          primaryDiagnosis: 'Deep Vein Thrombosis (DVT) & Pulmonary Embolism',
          outcome: 'DISCHARGED_IMPROVED',
          attendingPhysicianName: 'Dr. Hossam El-Din',
        },
      ],
      attendingPhysician: {
        staffId: '9042',
        name: 'Dr. Hossam El-Din',
        role: StaffRole.CONSULTANT,
      },
      primaryNurse: {
        staffId: '7721',
        name: 'RN Sarah Kamal',
        role: StaffRole.LEAD_RN,
      },
      isolationPrecautions: ['Airborne N95 Precautions'],
      createdAt: nowIso,
      updatedAt: nowIso,
    };

    const patient4: PatientDossier = {
      id: 'pat-04',
      mrn: '77810',
      fullNameEn: 'Mahmoud Taha',
      fullNameAr: 'محمود طه / سمير عزت',
      age: 67,
      gender: Gender.MALE,
      weightKg: 82,
      heightCm: 172,
      idealBodyWeightKg: 67.5,
      codeStatus: CodeStatus.FULL_CODE,
      primaryDiagnosisEn: 'Acute Coronary Syndrome (Post-PCI Stent) - Hemodynamically Stable',
      primaryDiagnosisAr: 'متلازمة الشريان التاجي الحادة بعد تركيب الدعامة',
      intakePathway: IntakePathway.FLOOR_TRANSFER,
      admissionDate: `${todayStr}T08:00:00.000Z`,
      currentBedId: BedNumber.BED_04,
      acuityLevel: AcuityLevel.STEP_DOWN,
      patientStatus: 'ACTIVE_ICU',
      allergies: [],
      microbiologyHistory: [],
      pastVisits: [],
      attendingPhysician: {
        staffId: '9115',
        name: 'Dr. Ahmed Tarek',
        role: StaffRole.SPECIALIST,
      },
      primaryNurse: {
        staffId: '7721',
        name: 'RN Sarah Kamal',
        role: StaffRole.LEAD_RN,
      },
      createdAt: nowIso,
      updatedAt: nowIso,
    };

    const patient5: PatientDossier = {
      id: 'pat-05',
      mrn: '44921',
      fullNameEn: 'Fatima Al-Zahraa',
      fullNameAr: 'فاطمة الزهراء / نادية منصور',
      age: 72,
      gender: Gender.FEMALE,
      weightKg: 64,
      heightCm: 158,
      idealBodyWeightKg: 50.5,
      codeStatus: CodeStatus.DNR,
      primaryDiagnosisEn: 'AE-COPD with Hypercapnic Respiratory Failure • BiPAP Weaning Day 2',
      primaryDiagnosisAr: 'تفاقم الانسداد الرئوي المزمن وفطام التنفس غير الغازي',
      intakePathway: IntakePathway.ER_REFERRAL,
      admissionDate: `${todayStr}T03:00:00.000Z`,
      currentBedId: BedNumber.BED_05,
      acuityLevel: AcuityLevel.GUARDED_STABLE,
      patientStatus: 'ACTIVE_ICU',
      allergies: [
        {
          id: 'all-05',
          allergen: 'NSAIDs (Ibuprofen / Diclofenac)',
          reaction: 'Acute Renal Exacerbation & Bronchospasm',
          severity: AllergySeverity.SEVERE,
          isLocked: true,
          verifiedBy: 'Dr. Ahmed Tarek',
        },
      ],
      microbiologyHistory: [],
      pastVisits: [],
      attendingPhysician: {
        staffId: '9115',
        name: 'Dr. Ahmed Tarek',
        role: StaffRole.SPECIALIST,
      },
      primaryNurse: {
        staffId: '7721',
        name: 'RN Sarah Kamal',
        role: StaffRole.LEAD_RN,
      },
      createdAt: nowIso,
      updatedAt: nowIso,
    };

    const patient6: PatientDossier = {
      id: 'pat-06',
      mrn: '11093',
      fullNameEn: 'Abdel-Nasser Ibrahim',
      fullNameAr: 'عبد الناصر إبراهيم',
      age: 61,
      gender: Gender.MALE,
      weightKg: 78,
      heightCm: 170,
      idealBodyWeightKg: 66.0,
      codeStatus: CodeStatus.FULL_CODE,
      primaryDiagnosisEn: 'End-stage Liver Cirrhosis • Acute Variceal Bleeding • Hemorrhagic Shock (Class III)',
      primaryDiagnosisAr: 'تليف كبدي متقدم، نزيف حاد بدوالي المريء وصدمة نزفية',
      intakePathway: IntakePathway.STAT_CRITICAL,
      admissionDate: `${todayStr}T00:30:00.000Z`,
      currentBedId: BedNumber.BED_06,
      acuityLevel: AcuityLevel.CRITICAL_STAT,
      patientStatus: 'ACTIVE_ICU',
      allergies: [
        {
          id: 'all-06',
          allergen: 'SULFA DRUGS (Sulfamethoxazole)',
          reaction: 'Severe Anaphylactic Reaction & Hypotension',
          severity: AllergySeverity.FATAL_ANAPHYLAXIS,
          isLocked: true,
          verifiedBy: 'Dr. Hossam El-Din',
        },
      ],
      microbiologyHistory: [],
      pastVisits: [
        {
          id: 'visit-06-1',
          admissionDate: '2024-05-10',
          dischargeDate: '2024-05-16',
          primaryDiagnosis: 'Decompensated Cirrhosis & Ascites',
          outcome: 'DISCHARGED_IMPROVED',
          attendingPhysicianName: 'Dr. Hossam El-Din',
        },
      ],
      attendingPhysician: {
        staffId: '9042',
        name: 'Dr. Hossam El-Din',
        role: StaffRole.CONSULTANT,
      },
      primaryNurse: {
        staffId: '7721',
        name: 'RN Sarah Kamal',
        role: StaffRole.LEAD_RN,
      },
      createdAt: nowIso,
      updatedAt: nowIso,
    };

    // Archived Patients (including 10-day auto-purge mortality cases)
    const deceasedPatient1: PatientDossier = {
      id: 'pat-mort-01',
      mrn: '81290',
      fullNameEn: 'Mahmoud Fouad Khalil',
      fullNameAr: 'محمود فؤاد خليل',
      age: 74,
      gender: Gender.MALE,
      weightKg: 70,
      heightCm: 168,
      idealBodyWeightKg: 64.0,
      codeStatus: CodeStatus.DNR,
      primaryDiagnosisEn: 'Refractory Septic Shock & Multi-Organ Failure secondary to Severe HAP',
      primaryDiagnosisAr: 'صدمة إنتانية معندة وفشل متعدد الأعضاء',
      intakePathway: IntakePathway.STAT_CRITICAL,
      admissionDate: '2026-09-02T10:00:00.000Z',
      acuityLevel: AcuityLevel.CRITICAL_STAT,
      patientStatus: 'EXPIRED_MORTALITY',
      allergies: [],
      microbiologyHistory: [],
      pastVisits: [],
      attendingPhysician: {
        staffId: '9042',
        name: 'Dr. Hossam El-Din',
        role: StaffRole.CONSULTANT,
      },
      primaryNurse: {
        staffId: '7721',
        name: 'RN Sarah Kamal',
        role: StaffRole.LEAD_RN,
      },
      mortalityRecord: {
        patientId: 'pat-mort-01',
        dateOfDeath: '2026-09-11',
        timeOfDeath: '03:45 AM',
        primaryCauseOfDeath: 'Refractory Septic Shock and Cardiopulmonary Arrest',
        secondaryCauses: ['Multi-Organ Dysfunction Syndrome', 'Hospital-Acquired Pneumonia'],
        supervisingConsultant: 'Dr. Hossam El-Din',
        deathSummaryNoteId: 'note-death-01',
        burialReportGenerated: true,
        autoPurgeScheduledAt: '2026-09-21T03:45:00.000Z', // Day 7 of 10
        isArchived: true,
        isPurged: false,
      },
      createdAt: '2026-09-02T10:00:00.000Z',
      updatedAt: '2026-09-11T04:00:00.000Z',
    };

    const deceasedPatient2: PatientDossier = {
      id: 'pat-mort-02',
      mrn: '72341',
      fullNameEn: 'Farida Abdel-Rahman Issa',
      fullNameAr: 'فريدة عبد الرحمن عيسى',
      age: 68,
      gender: Gender.FEMALE,
      weightKg: 62,
      heightCm: 156,
      idealBodyWeightKg: 49.0,
      codeStatus: CodeStatus.DNR,
      primaryDiagnosisEn: 'Massive Intracranial Hemorrhage & Brain Herniation post-Thrombolysis',
      primaryDiagnosisAr: 'نزيف دماغي حاد وانفتاق دماغي',
      intakePathway: IntakePathway.STAT_CRITICAL,
      admissionDate: `${todayStr}T02:00:00.000Z`,
      acuityLevel: AcuityLevel.CRITICAL_STAT,
      patientStatus: 'EXPIRED_MORTALITY',
      allergies: [],
      microbiologyHistory: [],
      pastVisits: [],
      attendingPhysician: {
        staffId: '9115',
        name: 'Dr. Sara El-Menshawy',
        role: StaffRole.CONSULTANT,
      },
      primaryNurse: {
        staffId: '7721',
        name: 'RN Sarah Kamal',
        role: StaffRole.LEAD_RN,
      },
      mortalityRecord: {
        patientId: 'pat-mort-02',
        dateOfDeath: todayStr,
        timeOfDeath: '08:20 AM',
        primaryCauseOfDeath: 'Brainstem Herniation and Irreversible Neurological Death',
        secondaryCauses: ['Massive Intracranial Hemorrhage'],
        supervisingConsultant: 'Dr. Sara El-Menshawy',
        deathSummaryNoteId: 'note-death-02',
        burialReportGenerated: true,
        autoPurgeScheduledAt: `${todayStr}T08:20:00.000Z`, // Day 1 of 10
        isArchived: true,
        isPurged: false,
      },
      createdAt: nowIso,
      updatedAt: nowIso,
    };

    const archivedPatient3: PatientDossier = {
      id: 'pat-arch-03',
      mrn: '68412',
      fullNameEn: 'Seyeda Mahmoud Abdel-Aal',
      fullNameAr: 'سيدة محمود عبد العال',
      age: 62,
      gender: Gender.FEMALE,
      weightKg: 74,
      heightCm: 162,
      idealBodyWeightKg: 53.5,
      codeStatus: CodeStatus.FULL_CODE,
      primaryDiagnosisEn: 'Diabetic Ketoacidosis (DKA) - Resolved + Non-STEMI (Cardiac Troponin Cleared)',
      primaryDiagnosisAr: 'حماض كيتوني سكري تم شفاؤه واحتشاء عضلة القلب دون ارتفاع ST',
      intakePathway: IntakePathway.ER_REFERRAL,
      admissionDate: '2026-09-08T14:00:00.000Z',
      acuityLevel: AcuityLevel.STEP_DOWN,
      patientStatus: 'DISCHARGED_STEPDOWN',
      allergies: [
        {
          id: 'all-arch-03',
          allergen: 'Iodinated Radiocontrast Media',
          reaction: 'Contrast-Induced Nephropathy Risk & Urticaria',
          severity: AllergySeverity.MODERATE,
          isLocked: true,
          verifiedBy: 'Dr. Hossam El-Din',
        },
      ],
      microbiologyHistory: [],
      pastVisits: [],
      attendingPhysician: {
        staffId: '9042',
        name: 'Dr. Hossam El-Din',
        role: StaffRole.CONSULTANT,
      },
      primaryNurse: {
        staffId: '7721',
        name: 'RN Sarah Kamal',
        role: StaffRole.LEAD_RN,
      },
      createdAt: '2026-09-08T14:00:00.000Z',
      updatedAt: '2026-09-12T16:00:00.000Z',
    };

    const archivedPatient4: PatientDossier = {
      id: 'pat-arch-04',
      mrn: '31908',
      fullNameEn: 'Ibrahim Mostafa Khalil',
      fullNameAr: 'إبراهيم مصطفى خليل',
      age: 70,
      gender: Gender.MALE,
      weightKg: 68,
      heightCm: 170,
      idealBodyWeightKg: 66.0,
      codeStatus: CodeStatus.FULL_CODE,
      primaryDiagnosisEn: 'End-Stage Renal Disease (ESRD) on HD + Heart Failure (HFrEF EF 25%)',
      primaryDiagnosisAr: 'فشل كلوي مزمن مرحلة نهائية على الغسيل الدموي وفشل قلبي متقدم',
      intakePathway: IntakePathway.ER_REFERRAL,
      admissionDate: '2026-08-25T11:00:00.000Z',
      acuityLevel: AcuityLevel.STEP_DOWN,
      patientStatus: 'DISCHARGED_HOME',
      allergies: [
        {
          id: 'all-arch-04',
          allergen: 'NSAIDs (Absolute Contraindication)',
          reaction: 'Renal shutdown',
          severity: AllergySeverity.FATAL_ANAPHYLAXIS,
          isLocked: true,
          verifiedBy: 'Dr. Hossam El-Din',
        },
      ],
      microbiologyHistory: [],
      pastVisits: [],
      attendingPhysician: {
        staffId: '9042',
        name: 'Dr. Hossam El-Din',
        role: StaffRole.CONSULTANT,
      },
      primaryNurse: {
        staffId: '7721',
        name: 'RN Sarah Kamal',
        role: StaffRole.LEAD_RN,
      },
      isFrequentFlyer: true,
      fluidRestrictionDailyMl: 1200,
      createdAt: '2026-08-25T11:00:00.000Z',
      updatedAt: '2026-09-01T10:00:00.000Z',
    };

    const archivedPatient5: PatientDossier = {
      id: 'pat-arch-05',
      mrn: '55104',
      fullNameEn: 'Zeinab Abdel-Hamid',
      fullNameAr: 'زينب عبد الحميد',
      age: 47,
      gender: Gender.FEMALE,
      weightKg: 65,
      heightCm: 164,
      idealBodyWeightKg: 55.0,
      codeStatus: CodeStatus.FULL_CODE,
      primaryDiagnosisEn: 'Acute Pancreatitis (Biliary etiology) - Lipase normalized, Ultrasound cleared',
      primaryDiagnosisAr: 'التهاب البنكرياس الحاد المراري - تحسن كامل',
      intakePathway: IntakePathway.ER_REFERRAL,
      admissionDate: '2026-09-04T12:00:00.000Z',
      acuityLevel: AcuityLevel.STEP_DOWN,
      patientStatus: 'DISCHARGED_HOME',
      allergies: [],
      microbiologyHistory: [],
      pastVisits: [],
      attendingPhysician: {
        staffId: '9042',
        name: 'Dr. Hossam El-Din',
        role: StaffRole.CONSULTANT,
      },
      primaryNurse: {
        staffId: '7721',
        name: 'RN Sarah Kamal',
        role: StaffRole.LEAD_RN,
      },
      createdAt: '2026-09-04T12:00:00.000Z',
      updatedAt: '2026-09-07T12:00:00.000Z',
    };

    await db.patients.bulkPut([
      patient1,
      patient2,
      patient3,
      patient4,
      patient5,
      patient6,
      deceasedPatient1,
      deceasedPatient2,
      archivedPatient3,
      archivedPatient4,
      archivedPatient5,
    ]);

    // 3. Bed Records (6 Pods)
    const bedRecords: BedRecord[] = [
      {
        bedNumber: BedNumber.BED_01,
        bayName: 'MICU Pod 01 (Isolation Positive Pressure)',
        status: BedStatus.OCCUPIED,
        currentPatientId: patient1.id,
        hardwareReadiness: {
          ventilatorCalibrated: true,
          ventilatorModel: 'Draeger Evita V800',
          telemetryZeroed: true,
          telemetryLead: 'Lead II (100 Hz)',
          wallSuctionTested: true,
          centralOxygenPsi: 50,
          alarisPumpsPurged: true,
          disposableKitsPrepped: true,
        },
        lastTelemetryPingUtc: nowIso,
      },
      {
        bedNumber: BedNumber.BED_02,
        bayName: 'MICU Pod 02 (Metabolic Resuscitation Bay)',
        status: BedStatus.OCCUPIED,
        currentPatientId: patient2.id,
        hardwareReadiness: {
          ventilatorCalibrated: true,
          ventilatorModel: 'Philips Respironics V60',
          telemetryZeroed: true,
          telemetryLead: 'Lead II',
          wallSuctionTested: true,
          centralOxygenPsi: 50,
          alarisPumpsPurged: true,
          disposableKitsPrepped: true,
        },
        lastTelemetryPingUtc: nowIso,
      },
      {
        bedNumber: BedNumber.BED_03,
        bayName: 'MICU Pod 03 (Advanced Shock & ARDS Bay)',
        status: BedStatus.OCCUPIED,
        currentPatientId: patient3.id,
        hardwareReadiness: {
          ventilatorCalibrated: true,
          ventilatorModel: 'Draeger Evita V800',
          telemetryZeroed: true,
          telemetryLead: 'Lead II (100 Hz)',
          wallSuctionTested: true,
          centralOxygenPsi: 50,
          alarisPumpsPurged: true,
          disposableKitsPrepped: true,
        },
        lastTelemetryPingUtc: nowIso,
      },
      {
        bedNumber: BedNumber.BED_04,
        bayName: 'MICU Pod 04 (Step-down & Weaning Bay)',
        status: BedStatus.TRANSFER_PENDING,
        currentPatientId: patient4.id,
        hardwareReadiness: {
          ventilatorCalibrated: true,
          ventilatorModel: 'Standby / High-Flow',
          telemetryZeroed: true,
          telemetryLead: 'Lead II',
          wallSuctionTested: true,
          centralOxygenPsi: 50,
          alarisPumpsPurged: true,
          disposableKitsPrepped: true,
        },
        lastTelemetryPingUtc: nowIso,
      },
      {
        bedNumber: BedNumber.BED_05,
        bayName: 'MICU Pod 05 (Pulmonary & Renal Bay)',
        status: BedStatus.OCCUPIED,
        currentPatientId: patient5.id,
        hardwareReadiness: {
          ventilatorCalibrated: true,
          ventilatorModel: 'Draeger Carina NIV',
          telemetryZeroed: true,
          telemetryLead: 'Lead II',
          wallSuctionTested: true,
          centralOxygenPsi: 50,
          alarisPumpsPurged: true,
          disposableKitsPrepped: true,
        },
        lastTelemetryPingUtc: nowIso,
      },
      {
        bedNumber: BedNumber.BED_06,
        bayName: 'MICU Pod 06 (Hepato-Biliary & GI Hemorrhage Bay)',
        status: BedStatus.OCCUPIED,
        currentPatientId: patient6.id,
        hardwareReadiness: {
          ventilatorCalibrated: true,
          ventilatorModel: 'Draeger Evita V800',
          telemetryZeroed: true,
          telemetryLead: 'Lead II (100 Hz)',
          wallSuctionTested: true,
          centralOxygenPsi: 50,
          alarisPumpsPurged: true,
          disposableKitsPrepped: true,
        },
        lastTelemetryPingUtc: nowIso,
      },
    ];
    await db.beds.bulkPut(bedRecords);

    // 4. Telemetry Vitals Seed
    const vitalsList: TelemetryVitals[] = [
      {
        id: 'vit-01',
        bedId: BedNumber.BED_01,
        patientId: patient1.id,
        timestamp: nowIso,
        heartRateBpm: 118,
        heartRhythm: 'Sinus Tachycardia',
        systolicBpMmHg: 90,
        diastolicBpMmHg: 60,
        meanArterialPressureMmHg: 70,
        isArterialLine: true,
        spo2Percent: 93,
        fio2SuppliedPercent: 70,
        respiratoryRateCpm: 24,
        coreTemperatureCelsius: 38.4,
        temperatureSite: 'FOLEY_CORE',
        gcsTotalScore: 10,
        gcsBreakdown: { eyeOpening: 3, verbalResponse: 1, motorResponse: 6, isExtubatedOrTrach: false },
        sedationRassScore: -3,
        lactateMmolPerL: 3.4,
        lactateClearancePercent: 18,
        recordedBy: { staffId: '7721', name: 'RN Sarah Kamal', role: StaffRole.LEAD_RN },
      },
      {
        id: 'vit-02',
        bedId: BedNumber.BED_02,
        patientId: patient2.id,
        timestamp: nowIso,
        heartRateBpm: 78,
        heartRhythm: 'Normal Sinus Rhythm',
        systolicBpMmHg: 125,
        diastolicBpMmHg: 75,
        meanArterialPressureMmHg: 91,
        isArterialLine: false,
        spo2Percent: 98,
        fio2SuppliedPercent: 28,
        respiratoryRateCpm: 16,
        coreTemperatureCelsius: 37.1,
        temperatureSite: 'AXILLARY',
        gcsTotalScore: 15,
        gcsBreakdown: { eyeOpening: 4, verbalResponse: 5, motorResponse: 6 },
        bloodGlucoseMgDl: 184,
        recordedBy: { staffId: '7721', name: 'RN Sarah Kamal', role: StaffRole.LEAD_RN },
      },
      {
        id: 'vit-03',
        bedId: BedNumber.BED_03,
        patientId: patient3.id,
        timestamp: nowIso,
        heartRateBpm: 124,
        heartRhythm: 'Sinus Tachycardia',
        systolicBpMmHg: 92,
        diastolicBpMmHg: 52,
        meanArterialPressureMmHg: 65,
        isArterialLine: true,
        spo2Percent: 94,
        fio2SuppliedPercent: 60,
        respiratoryRateCpm: 22,
        coreTemperatureCelsius: 38.6,
        temperatureSite: 'FOLEY_CORE',
        gcsTotalScore: 10,
        gcsBreakdown: { eyeOpening: 3, verbalResponse: 1, motorResponse: 6, isExtubatedOrTrach: false },
        sedationRassScore: -2,
        lactateMmolPerL: 3.8,
        lactateClearancePercent: 26,
        recordedBy: { staffId: '7721', name: 'RN Sarah Kamal', role: StaffRole.LEAD_RN },
      },
      {
        id: 'vit-06',
        bedId: BedNumber.BED_06,
        patientId: patient6.id,
        timestamp: nowIso,
        heartRateBpm: 100,
        heartRhythm: 'Sinus Tachycardia',
        systolicBpMmHg: 95,
        diastolicBpMmHg: 55,
        meanArterialPressureMmHg: 68,
        isArterialLine: true,
        spo2Percent: 98,
        fio2SuppliedPercent: 50,
        respiratoryRateCpm: 18,
        coreTemperatureCelsius: 37.4,
        temperatureSite: 'FOLEY_CORE',
        gcsTotalScore: 14,
        gcsBreakdown: { eyeOpening: 4, verbalResponse: 4, motorResponse: 6 },
        sedationRassScore: 0,
        lactateMmolPerL: 3.1,
        recordedBy: { staffId: '7721', name: 'RN Sarah Kamal', role: StaffRole.LEAD_RN },
      },
    ];
    await db.vitals.bulkPut(vitalsList);

    // 5. Ventilator Settings Seed
    const ventList: VentilatorParameters[] = [
      {
        id: 'vent-03',
        bedId: BedNumber.BED_03,
        patientId: patient3.id,
        timestamp: nowIso,
        deviceModel: 'Draeger Evita V800',
        mode: VentilatorMode.PRVC_AC,
        fio2Percent: 60,
        peepCmH2O: 10,
        tidalVolumeMl: 440,
        peakInspiratoryPressureCmH2O: 26,
        plateauPressureCmH2O: 21,
        drivingPressureCmH2O: 11,
        setRespiratoryRateCpm: 20,
        actualRespiratoryRateCpm: 22,
        circuitLeakPercent: 0,
        recordedByStaffName: 'RT Omar & Dr. Hossam El-Din',
      },
      {
        id: 'vent-06',
        bedId: BedNumber.BED_06,
        patientId: patient6.id,
        timestamp: nowIso,
        deviceModel: 'Draeger Evita V800',
        mode: VentilatorMode.SIMV_PC,
        fio2Percent: 50,
        peepCmH2O: 6,
        tidalVolumeMl: 440,
        peakInspiratoryPressureCmH2O: 22,
        plateauPressureCmH2O: 18,
        drivingPressureCmH2O: 12,
        setRespiratoryRateCpm: 16,
        actualRespiratoryRateCpm: 18,
        circuitLeakPercent: 0,
        recordedByStaffName: 'Dr. Hossam El-Din',
      },
    ];
    await db.ventilators.bulkPut(ventList);

    // 6. Infusion Pumps Seed
    const pumpsList: InfusionPumpLine[] = [
      {
        id: 'pump-01-norad',
        bedId: BedNumber.BED_01,
        patientId: patient1.id,
        pumpChannel: 'PUMP_A',
        lineAccessType: 'CVC_LINE_1',
        drugNameEn: 'Noradrenaline Infusion',
        drugNameAr: 'نورأدرينالين',
        solutionCarrier: '4 mg in 50 mL D5W',
        currentRate: 0.15,
        rateUnit: 'mcg/kg/min',
        flowRateMlPerHour: 6.2,
        status: PumpStatus.TITRATING,
        clinicalTargetDescription: 'Titrate for MAP > 65 mmHg',
        remainingVolumeMl: 28,
        totalVolumeMl: 50,
      },
      {
        id: 'pump-03-norad',
        bedId: BedNumber.BED_03,
        patientId: patient3.id,
        pumpChannel: 'PUMP_A',
        lineAccessType: 'CVC_LINE_1',
        drugNameEn: 'Noradrenaline',
        drugNameAr: 'نورأدرينالين',
        solutionCarrier: '4 mg in 50 mL D5W',
        currentRate: 0.12,
        rateUnit: 'mcg/kg/min',
        flowRateMlPerHour: 5.4,
        status: PumpStatus.TITRATING,
        clinicalTargetDescription: 'Maintain MAP >= 65 mmHg',
        remainingVolumeMl: 34,
        totalVolumeMl: 50,
      },
      {
        id: 'pump-03-vaso',
        bedId: BedNumber.BED_03,
        patientId: patient3.id,
        pumpChannel: 'PUMP_B',
        lineAccessType: 'CVC_LINE_2',
        drugNameEn: 'Vasopressin',
        drugNameAr: 'فازوبريسين',
        solutionCarrier: '20 Units in 100 mL NS',
        currentRate: 0.03,
        rateUnit: 'Units/hr',
        flowRateMlPerHour: 2.4,
        status: PumpStatus.RUNNING,
        clinicalTargetDescription: 'Fixed-rate adjuvant vasopressor for Septic Shock',
        remainingVolumeMl: 65,
        totalVolumeMl: 100,
      },
      {
        id: 'pump-03-prop',
        bedId: BedNumber.BED_03,
        patientId: patient3.id,
        pumpChannel: 'PUMP_C',
        lineAccessType: 'CVC_LINE_3',
        drugNameEn: 'Propofol 1%',
        drugNameAr: 'بروبوفول للتخدير',
        solutionCarrier: '1000 mg in 100 mL emulsion',
        currentRate: 15,
        rateUnit: 'mcg/kg/min',
        flowRateMlPerHour: 7.5,
        status: PumpStatus.RUNNING,
        clinicalTargetDescription: 'Synchronize mechanical ventilation (Target RASS -2)',
        remainingVolumeMl: 45,
        totalVolumeMl: 100,
      },
      {
        id: 'pump-06-oct',
        bedId: BedNumber.BED_06,
        patientId: patient6.id,
        pumpChannel: 'PUMP_A',
        lineAccessType: 'CVC_LINE_1',
        drugNameEn: 'Octreotide (Sandostatin)',
        drugNameAr: 'أوكتريوتيد',
        solutionCarrier: '500 mcg in 50 mL NS',
        currentRate: 50,
        rateUnit: 'mcg/h',
        flowRateMlPerHour: 5.0,
        status: PumpStatus.RUNNING,
        clinicalTargetDescription: 'Continuous splanchnic vasoconstriction for Variceal Bleed',
        remainingVolumeMl: 22,
        totalVolumeMl: 50,
      },
      {
        id: 'pump-06-norad',
        bedId: BedNumber.BED_06,
        patientId: patient6.id,
        pumpChannel: 'PUMP_B',
        lineAccessType: 'CVC_LINE_2',
        drugNameEn: 'Noradrenaline',
        drugNameAr: 'نورأدرينالين',
        solutionCarrier: '4 mg in 50 mL D5W',
        currentRate: 0.08,
        rateUnit: 'mcg/kg/min',
        flowRateMlPerHour: 4.7,
        status: PumpStatus.TITRATING,
        clinicalTargetDescription: 'Target MAP > 65 mmHg',
        remainingVolumeMl: 30,
        totalVolumeMl: 50,
      },
      {
        id: 'pump-06-panto',
        bedId: BedNumber.BED_06,
        patientId: patient6.id,
        pumpChannel: 'PUMP_C',
        lineAccessType: 'PERIPHERAL',
        drugNameEn: 'Pantoprazole (Protonix)',
        drugNameAr: 'بانتوبرازول',
        solutionCarrier: '80 mg in 100 mL NS',
        currentRate: 8.0,
        rateUnit: 'mg/h',
        flowRateMlPerHour: 10.0,
        status: PumpStatus.RUNNING,
        clinicalTargetDescription: 'Continuous high-dose PPI for GI mucosal protection',
        remainingVolumeMl: 55,
        totalVolumeMl: 100,
      },
    ];
    await db.infusionPumps.bulkPut(pumpsList);

    // 7. Fluid Balances Seed
    const fluidList: FluidBalance24H[] = [
      {
        id: 'fb-03',
        bedId: BedNumber.BED_03,
        patientId: patient3.id,
        periodStartTimestamp: `${todayStr}T00:00:00.000Z`,
        periodEndTimestamp: nowIso,
        intakeBreakdown: {
          ivMaintenanceFluidMl: 600,
          ivMedicationInfusionsMl: 450,
          enteralFeedingMl: 0,
          bloodProductsMl: 0,
          oralFluidsMl: 0,
          totalIntakeMl: 1850,
        },
        outputBreakdown: {
          urineOutputMl: 380,
          hourlyUrineAverageMlPerHour: 45,
          nasogastricDrainageMl: 40,
          chestTubeDrainageMl: 0,
          surgicalDrainageMl: 0,
          totalOutputMl: 420,
        },
        netCumulativeBalanceMl: 1430,
        recordedByStaffName: 'RN Sarah Kamal',
      },
      {
        id: 'fb-06',
        bedId: BedNumber.BED_06,
        patientId: patient6.id,
        periodStartTimestamp: `${todayStr}T00:00:00.000Z`,
        periodEndTimestamp: nowIso,
        intakeBreakdown: {
          ivMaintenanceFluidMl: 1000,
          ivMedicationInfusionsMl: 450,
          enteralFeedingMl: 0,
          bloodProductsMl: 1000,
          oralFluidsMl: 0,
          totalIntakeMl: 2450,
        },
        outputBreakdown: {
          urineOutputMl: 1450,
          hourlyUrineAverageMlPerHour: 60,
          nasogastricDrainageMl: 370,
          chestTubeDrainageMl: 0,
          surgicalDrainageMl: 0,
          totalOutputMl: 1820,
        },
        netCumulativeBalanceMl: 630,
        recordedByStaffName: 'RN Sarah Kamal',
      },
    ];
    await db.fluidBalances.bulkPut(fluidList);

    // 8. Transfusions & Blood Bank Seed
    const transfusionsList: TransfusionTracker[] = [
      {
        id: 'trans-06',
        bedId: BedNumber.BED_06,
        patientId: patient6.id,
        bloodGroup: 'O+',
        rhFactor: 'POSITIVE',
        crossmatchStatus: 'ACTIVE',
        activeProtocol: 'MASSIVE_TRANSFUSION_PROTOCOL',
        units: [
          {
            unitId: 'PRBC-2026-991',
            productType: TransfusionProduct.PRBC,
            volumeMl: 300,
            status: 'COMPLETED',
            startedAt: `${todayStr}T01:00:00.000Z`,
            completedAt: `${todayStr}T03:00:00.000Z`,
            administeredByRN: 'RN Sarah Kamal',
          },
          {
            unitId: 'PRBC-2026-992',
            productType: TransfusionProduct.PRBC,
            volumeMl: 300,
            status: 'COMPLETED',
            startedAt: `${todayStr}T03:15:00.000Z`,
            completedAt: `${todayStr}T05:15:00.000Z`,
            administeredByRN: 'RN Sarah Kamal',
          },
          {
            unitId: 'FFP-2026-101',
            productType: TransfusionProduct.FFP,
            volumeMl: 250,
            status: 'READY_IN_BLOOD_BANK',
          },
          {
            unitId: 'FFP-2026-102',
            productType: TransfusionProduct.FFP,
            volumeMl: 250,
            status: 'READY_IN_BLOOD_BANK',
          },
          {
            unitId: 'FFP-2026-103',
            productType: TransfusionProduct.FFP,
            volumeMl: 250,
            status: 'PENDING_CROSSMATCH',
          },
          {
            unitId: 'FFP-2026-104',
            productType: TransfusionProduct.FFP,
            volumeMl: 250,
            status: 'PENDING_CROSSMATCH',
          },
        ],
        prbcUnitsInfusedCount: 2,
        prbcUnitsTotalOrdered: 2,
        ffpUnitsInfusedCount: 0,
        ffpUnitsTotalOrdered: 4,
        plateletsUnitsInfusedCount: 0,
        plateletsUnitsTotalOrdered: 0,
        latestHemoglobinGPerDl: 7.2,
        hemoglobinTrend12H: [
          { timestamp: '02:00', valueGPerDl: 6.4, label: 'STAT Admission' },
          { timestamp: '08:00', valueGPerDl: 6.8, label: 'Post Unit 1 PRBC' },
          { timestamp: '14:00', valueGPerDl: 7.2, label: 'Post Unit 2 PRBC' },
        ],
      },
    ];
    await db.transfusions.bulkPut(transfusionsList);

    // 9. SBAR Handovers Seed
    const sbarList: SbarHandoverReport[] = [
      {
        id: 'sbar-03',
        bedId: BedNumber.BED_03,
        patientId: patient3.id,
        shiftType: 'NIGHT',
        shiftDate: todayStr,
        shiftStartTime: '20:00',
        shiftEndTime: '08:00',
        outgoingDoctor: {
          staffId: '9042',
          name: 'Dr. Hossam El-Din',
          role: StaffRole.CONSULTANT,
          signedAt: `${todayStr}T07:45:00.000Z`,
          digitalSignatureToken: 'TOKEN:#ICU-SIGN-9921-HOSSAM',
        },
        situation: '62yo male admitted via ER with severe septic shock and ARDS, intubated on Draeger V800 PRVC mode. Ongoing dual vasopressor resuscitation.',
        background: 'Type 2 Diabetes Mellitus, HTN 12y, Prior ICU stay 2021 for DVT. Documented anaphylaxis to Penicillins. Started on IV Meropenem 1g q8h + Vancomycin adjusted to trough levels.',
        assessment: {
          hemodynamics: 'MAP 65 on Noradrenaline 0.12 mcg/kg/min + Vasopressin 0.03 u/min fixed rate. Peripheral perfusion warming.',
          pulmonaryAndAirway: 'pH 7.28, pCO2 48, pO2 78, HCO3 19, BE -6. PaO2/FiO2 ratio: 130 (Moderate-Severe ARDS). Lung protective ventilation active.',
          metabolicAndRenal: 'Cumulative 12h fluid balance +1,450 mL. UO average 38 mL/hr over past 3h.',
          neurologyAndSedation: 'Sedated on Propofol 15 mcg/kg/min (RASS -2). Pupils equal and reactive.',
          infectiousDiseaseAndAntibiotics: 'Blood cultures drawn x2. Meropenem started. Procalcitonin 14.8 ng/mL.',
        },
        recommendationAndOrders: [
          'Repeat STAT ABG and Serum Lactate in 2 hours (10:00).',
          'Bedside Focused Echocardiography at 09:00 for RV strain & fluid responsiveness.',
          'Target hourly Urine Output >45 mL/hr; initiate low-dose furosemide infusion if oliguria persists.',
          'Maintain MAP >= 65 mmHg strictly via Noradrenaline titration.',
        ],
        isLocked: true,
        cryptographicHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      },
    ];
    await db.sbarHandovers.bulkPut(sbarList);

    // 10. Clinical Notes and Addendums Seed
    const initialNote: ClinicalNote = {
      id: 'note-03-adm',
      bedId: BedNumber.BED_03,
      patientId: patient3.id,
      noteType: NoteType.ADMISSION_NOTE,
      title: 'MICU Admission & Initial Resuscitation Plan',
      content: 'Patient admitted directly from ER resuscitation room with severe septic shock 2ry to bilateral community-acquired pneumonia. Radial arterial line and right internal jugular triple-lumen CVC established under ultrasound guidance. Protective mechanical ventilation initiated (ARDSNet 6 mL/kg IBW). Strict Penicillin avoidance enforced in EHR.',
      authorId: 'staff-01',
      authorName: 'Dr. Hossam El-Din',
      authorRole: StaffRole.CONSULTANT,
      authorStaffId: '9042',
      timestamp: `${todayStr}T02:00:00.000Z`,
      isImmutable: true,
      cryptographicHash: 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3',
      digitalSignatureToken: 'SIGN-HOSSAM-CONSULTANT-0x9B44',
      addendums: [
        {
          id: 'add-03-01',
          noteId: 'note-03-adm',
          patientId: patient3.id,
          authorId: 'staff-02',
          authorName: 'Dr. Ahmed Tarek',
          authorRole: StaffRole.SPECIALIST,
          authorStaffId: '9115',
          timestamp: `${todayStr}T04:30:00.000Z`,
          content: 'Addendum: Central venous blood gas correlated with arterial line ABG. ScvO2 measured at 68%. Echocardiography technician confirmed for morning bedside scan.',
          reasonForAddendum: 'CLINICAL_UPDATE',
          previousHash: 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3',
          cryptographicSignature: 'c8f7d98302f3a8b30f40d8291a03948572019485720193847291048572019485',
          isImmutable: true,
        },
      ],
    };
    await db.clinicalNotes.bulkPut([initialNote]);

    // 11. Initial Audit Log
    const auditInit: WardAuditLog = {
      id: 'audit-001',
      timestamp: nowIso,
      eventType: 'PATIENT_ADMITTED',
      performedBy: {
        staffId: '9042',
        name: 'Dr. Hossam El-Din',
        role: StaffRole.CONSULTANT,
      },
      targetBedId: BedNumber.BED_03,
      targetPatientMrn: patient3.mrn,
      description: 'Patient Mohamed Adel El-Sayed admitted to Bed 03. Telemetry and ventilator synchronization verified.',
      immutableHash: 'f40d8291a03948572019485720193847291048572019485c8f7d98302f3a8b30',
    };
    await db.auditLogs.bulkPut([auditInit]);
  });
}
